### ISSUE TITLE
Could you help me with this error?

### ISSUE THREAD

**Issue by LucyPost** [richard-unterberg/leaflet-nextjs-ts-starter#23]
Hi, when I try to use next and leaflet at the same time, using components in leaflet always raises window is not defined error, do you know how to fix it?
The full error report is as follows
ReferenceError: window is not defined
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js:229:19)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js:7:11)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js:9:3)
    at (rsc)/./node_modules/.pnpm/leaflet@1.9.4/node_modules/leaflet/dist/leaflet-src.js (C:\new_folder\js_project\bookstroemap\.next\server\vendor-chunks\leaflet@1.9.4.js:19:1)     
    at __webpack_require__ (C:\new_folder\js_project\bookstroemap\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/page.tsx:7:65)
    at (rsc)/./app/page.tsx (C:\new_folder\js_project\bookstroemap\.next\server\app\page.js:184:1)
    at Function.__webpack_require__ (C:\new_folder\js_project\bookstroemap\.next\server\webpack-runtime.js:33:43)
    at async e7 (C:\new_folder\js_project\bookstroemap\node_modules\.pnpm\next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:396786)
    at async tS (C:\new_folder\js_project\bookstroemap\node_modules\.pnpm\next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:400444)
    at async tw (C:\new_folder\js_project\bookstroemap\node_modules\.pnpm\next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:401005)
    at async tw (C:\new_folder\js_project\bookstroemap\node_modules\.pnpm\next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:35:401136)
    at async tO (C:\new_folder\js_project\bookstroemap\node_modules\.pnpm\next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2130)
    at async C:\new_folder\js_project\bookstroemap\node_modules\.pnpm\next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:36:2722 {
  digest: '3437864959',
  page: '/'
}

**Comment by richard-unterberg** [comment]
@LucyPost sorry for the delay - can you confirm that this occurs, when you check out a fresh copy of the repo and after install and running dev mode?

if this is not the case - can you prepare a reproduction-repo for your custom code here on github? My first guess by only seeing this error is that you try to import leaflet on the server-side (e.g: code somewhere in you page component), which is not possible since `window` is client-side.

**Comment by richard-unterberg** [comment]
@LucyPost please check that your components are not directly importing the leaflet library, you only wanna access our referenced map like this, because by design most of `next.js`´ code runs on the server side, where `window` is not available:

```ts
  const { map } = useMapContext()
```

the idea behind this approach is to "bake" the map into the context and use the instance from there, instead of always initializing new map instances, because it requires rigorous checking if we are on the server or client side.

**Comment by LucyPost** [comment]
@richard-unterberg I'm not sure if it's the repo not being updated that's causing the problem, But I was able to trigger this by adding only the following code to the page.
`'use client'

import { LatLng } from "leaflet";

export default function Home() {

  const position = new LatLng(0, 0);

  return (
    <main className="flex min-h-screen flex-col">
      
    </main>
  );
}`
However, it seems that this problem can be avoided by using LatLngExpression or importing with dynamic.

**Comment by richard-unterberg** [comment]
If I remember correctly; Page templates in next.js are by design on the server side - even if you turn of SSR or use the directive the page is at least generated on the server anyway.

assuming you wanna only use GEOJson operations from leaflet on pages other than where map and it's context is initialized?

First question: just curious, for what do you need geospatial processing on a page template without using the map? Asking because importing the heavy leaflet client lib for only using a geojson operation feels odd. leaflet's main purpose is to display a map and it's markers and in our ssr/ssg next.js it's considered as kinda oddball and performance bottleneck - we only load it, when needed.

Therefore I wrapped the map related parts into a `<MapContextProvider />` which is brought by this hook:

```ts
// map: an instance from the map - for e.g.: map.on('moveend', ....)
// leafletLib: an instance of the whole leaflet library, which was also used to create the 'map' instance
const { leafletLib, map } = useMapContext()
const point = leafletLib.LatLng(...)
```
ref: [useMapContext()](https://github.com/richard-unterberg/leaflet-nextjs-ts-starter/blob/master/src/components/Map/useMapContext.ts)

At the moment, this context is only available on the `map` page.

Using a child component in the start page where you use the  'use client'  directive or as you already mentioned dynamic import are valid workarounds. The bigger downside of them are; user has to download a lot of js payload from leaflet only to calculate/type a simple bound like [LatLng](https://leafletjs.com/reference.html#latlng). If that makes no difference, because the user flow will lead or come from the map, then it's maybe a valid approach.

If you need to process geoJson data outside the map context consider a lib which does that in the first place like [turf.js](https://github.com/Turfjs/turf), also to overcome the `window is not defined` problem for a geojson operations. it also re-enables the possibility to outsource the calculations to the server side by design, but that strongly depends on where you get you marker data from.

*note that in turf.js calculations are in longitude / latitude
let me know if you need further help.

**Comment by LucyPost** [comment]
Thanks, I've actually only started working with nextjs in the last few months and still have a vague understanding of many of the concepts, your explanation has made me realise that the way I've been using the maps seems to have been too brute force, I'll be coming back to refer to your comments and the public repositories if I intend to optimise my project after that. But I'm just working on a classwork-like project at the moment, so I'll probably leave it alone once I get the functionality done.
This project is also in my public repository: bookstoremap, and I've tried to put it on vercel:https://bookstroemap.vercel.app/, but its incomplete at the moment and doesn't adapt to different screen sizes

**Comment by richard-unterberg** [comment]
@LucyPost - what's the status here. do you need support with that?
